### ISSUE TITLE
Define thoroughly the iai design principles

### ISSUE THREAD

**Issue by lorenzogrv** [laconbass/iai#1]
~~This issue belongs to project's [Life Cycle](https://github.com/laconbass/iai/wiki/Life-Cycle) Planning Phase.~~ outdated assumption

> This definition is being written on the [Design Principles](https://github.com/laconbass/iai/wiki/Design-Principles) document at the wiki.

**TODO**
- [ ] READ section should be improved as it's guru text now
- [ ] Avoid known blunders:
  - [ ](introduction) Note this section is heavily based on resources from the c2 wiki
  - [ ] Refactor _avoid prematurity_ (cause=generalization) (premature generalization=rule of thumb)
- [ ] OOD principles
  - [ ] Introduction should note this is mostly based on "uncle Bob"'s work
  - [ ] Forget that class -> builder thing, and just apply principles to every **software entity**
  - [ ] Most principles that note an "unexistant" rule of thumb, already have one. Refactor to provide them.
- [ ] Review the full document and note every author on the contrib page (unaware contributors)
- [ ] Triage this issue comments and migrate them to an "Architecture" issue when it proceeds.
- [ ] The document does not render as expected with the firefox extension I'm currently ussing to render local .md files. Related to embeded html tags for navigation. This concerts the HTML5MD convention.

> It seems that the "design principles" document is going too wide.
> **architecture design principles should fit on the same place than object oriented design principles?**
> **principles to avoid known blunders should fit on the same place than other design principles?**
> 
> _(laconbass @ January 2015)_

---

> OOD principles seem to be _an architecture thing_. READ seems better titled as _Principles for research_. The READ introduction seems the manifesto, the _origins_ of principles. Are principles a tool? Sure
> 
> @laconbass, February 2016

**Comment by laconbass** [comment]
[the twelve-factor app]: http://12factor.net/
[Martin Fowler]: http://martinfowler.com/
[Patterns of Enterprise Application Architecture]: http://books.google.com/books/about/Patterns_of_enterprise_application_archi.html?id=FyWZt5DdvFkC
[Refactoring]: http://books.google.com/books/about/Refactoring.html?id=1MsETFPD3I0C

After researching [the twelve-factor app] "manifesto", the titles of two books written by [Martin Fowler] shine:

- [Patterns of Enterprise Application Architecture] (2003)
- [Refactoring] (1999)

**Comment by laconbass** [comment]
[principles of design]: https://www.getty.edu/education/teachers/building_lessons/principles_design.pdf
[J. Paul Getty Trust]: http://www.getty.edu/about/mission.html

Nice paper about the [principles of design] that summarizes well **the use the elements of art in a work of art** _([J. Paul Getty Trust] 2011)_.

**Comment by laconbass** [comment]
Working hard on **avoid known blunders**. I'm basing the research heavily on the c2 wiki, but I should grab information also on other places.

**Comment by laconbass** [comment]
Commited changes just now, added some TODOs. I should move forward and see how changes affect the planning, and come back later.

It must be determined if *the twelve-factor app* thing fits here or not.

**Comment by lorenzogrv** [comment]
While drafting the data validation layer, I met the concept of [_Inversion of control_](http://en.wikipedia.org/wiki/Inversion_of_control). It is related to the dependency inversion principle, but not the same. While researching the concept I found an awesome paper called [_Designing Reusable Classes_](http://www.laputan.org/drc/drc.html) that offers some clues (rules).

Jumping here and there, I've met the [_Law of Demeter_](http://en.wikipedia.org/wiki/Law_of_Demeter). The [_original paper_](http://www.ccs.neu.edu/research/demeter/papers/law-of-demeter/oopsla88-law-of-demeter.pdf) is available, for my pleassure.

More architecture related, and data-validation too, [Strategy](http://en.wikipedia.org/wiki/Strategy_pattern) seems a nice pattern to suffice my thoughs about the complexity of validating complex structures but it's time to make an effort on providing just the features needed at this moment (simplifying), and refactor later if need, **applying YAGNI**.
