### ISSUE TITLE
Define thoroughly the iai goals

### ISSUE THREAD

**Issue by lorenzogrv** [laconbass/iai#2]
**TODO**
- [ ] Refactor this issue summary to something like the #1 summary
- [ ] Goals document should precede the Design Principles document on the Life Cycle.
- [ ] Goals is missing a "Productivity Goals" section, values related to time measures, effectivenesses to reduce time requeriments.
- [ ] Review the "agile" goal, the argument is: Agile has been demostrated to be... by the software industr.... blabla ~~Methodology driven + agile is the same, refactor that~~
  - http://www.mountaingoatsoftware.com/agile/user-stories
  - http://www.mountaingoatsoftware.com/agile/planning-poker
- [x] Currently, the readme file on the 1.0.0-alpha branch mixes the goals with some principles, with stuff that seems more likely a feature list. This must be splited accordingly, cleaned up (removing things that do not belong there if need), and documented on [the wiki](https://github.com/laconbass/iai/wiki)

> It seems that the "goals" document **should be not _aka. requeriments_**.
> **requeriments seems a thing more specific while goals should be wider.**
> 
>  _(laconbass @ January 2015)_

**Comment by lorenzogrv** [comment]
So the whole thing is a big goal: **maintain the attitude**, that connects the idea and philosophy with the goals document. The goals document should explain how it's supossed the program will help on maintaning the attitude.
